name: 定时采集

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Actions'
        required: false
        default: 'false'

  schedule:
    - cron: 0 */6 * * *

  watch:
    types: started

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: 拉取代码
      - uses: actions/checkout@v2
        with:
          ref: io

      - name: Go 环境
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: 运行
        run: go run main.go

      - name: 提交
        run: |
          git config --local user.email "25251993@qq.com"
          git config --local user.name "iii6"
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') 更新订阅链接"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ github.ref }}
